### ISSUE TITLE
Cannot get to run

### ISSUE THREAD

**Issue by mlasham** [tdack/unifi-parental#1]
Hi, when I try to run this  I get the following errors:

any ideas what I could have done wrong?
 

unifi-parental@0.0.1 start /home/pi/Downloads/unifi-parental-master
> node index.js

/home/pi/Downloads/unifi-parental-master/index.js:34
nodeCleanup( (exitCode, signal) => {
                                 ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! unifi-parental@0.0.1 start: `node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the unifi-parental@0.0.1 start script.
npm ERR! This is most likely a problem with the unifi-parental package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls unifi-parental
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.24-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Downloads/unifi-parental-master
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by mlasham** [comment]
[npm-debug.log](https://github.com/tdack/unifi-parental/files/1629109/npm-debug.log)

**Comment by tdack** [comment]
It looks like you are using a very old version of NodeJS, v0.10.x is End of Life - see [NodeJS Release schedule](https://github.com/nodejs/Release#release-schedule).
 
This code was written and tested against Node v6.11.1 which the previous Long Term Support version, and it should work against NodeJS v8.9.x which is the current LTS.

In short, you need a newer version of NodeJS - see https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions for installation instructions.

I'll update the README to reflect this.
