### ISSUE TITLE
UniFi Security Gateway 3P

### ISSUE THREAD

**Issue by mtriber** [tdack/unifi-parental#4]
Will this work with my UniFi Security Gateway 3P? How do I install this? on the unit?

**Comment by tdack** [comment]
It will work with your USG 3P, however, it needs to run on another machine on your network with access to your Unifi Controller.

It doesn't run on the USG.

**Comment by mtriber** [comment]
Sorry to ask, what type of machine is this? Could you be more specific how
this works.


Thanks,
Mike Triber
508-254-4649 Cell
mrt@thecomputerlink.com

**Comment by mtriber** [comment]
Hello,

Is it possible I could pay you to implement this feature in my device?

**Comment by tdack** [comment]
Sorry I don't really have the time to be able to do this.

I currently have it installed on a machine running Linux. You could run it in a Linux virtual machine, or even on a cloud based virtual machine.

This "software" is really a bit of a kludge to meet some specific needs I had. It is not pretty or refined, and more than likely to break without warning. If you haven't the knowledge to install it, then keeping it running would be even harder.

Cheers,
   Troy
